const FONTS = {
  ui: "var(--font-ui)",
  mono: "var(--font-code)",
  display: "var(--font-ui)",
};

const TEXT = {
  xs: "var(--text-xs)",
  sm: "var(--text-sm)",
  md: "var(--text-md)",
  code: "var(--text-code)",
};

const C = {
  bg: "var(--bg-app)",
  surface1: "var(--surface-1)",
  surface2: "var(--surface-2)",
  border: "var(--border)",
  borderStrong: "var(--border-strong)",
  text: "var(--text)",
  textStrong: "var(--text-strong)",
  muted: "var(--muted)",
  dim: "var(--dim)",
  faint: "var(--faint)",
};

const ACCENT = "var(--accent)";
const CARD_BG = C.surface1;
const CARD = {
  background: CARD_BG,
  borderWidth: 1,
  borderStyle: "solid",
  borderColor: C.border,
  boxShadow: "var(--shadow-soft)",
};

export const S = {
  root: {
    minHeight: "100vh",
    width: "100%",
    color: C.text,
    fontFamily: FONTS.ui,
    fontSize: TEXT.md,
    lineHeight: 1.55,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "0 16px 48px",
    animation: "fadeIn 0.4s ease",
  },

  menuContainer: { width: "100%", maxWidth: 520, display: "flex", flexDirection: "column", gap: 16 },
  menuTopbar: { width: "100%", display: "flex", justifyContent: "space-between", alignItems: "center", padding: "20px 0 16px", animation: "fadeSlideIn 0.4s ease both" },
  menuUserInfo: { display: "flex", alignItems: "center", gap: 10, minWidth: 0 },
  menuAvatar: {
    width: 32,
    height: 32,
    borderRadius: 999,
    background: "linear-gradient(135deg, var(--accent), var(--info))",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: FONTS.display,
    fontWeight: 700,
    fontSize: 14,
    color: "var(--bg-page)",
    flexShrink: 0,
  },
  menuUsername: { fontFamily: FONTS.ui, fontSize: 14, color: C.muted, fontWeight: 500, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  menuSignout: { fontFamily: FONTS.mono, fontSize: 13, color: C.faint, background: "none", border: `1px solid ${C.border}`, borderRadius: 8, padding: "6px 12px", cursor: "pointer" },

  brand: { textAlign: "center", padding: "20px 0 8px", animation: "fadeSlideIn 0.4s ease 0.1s both" },
  logo: { fontFamily: FONTS.display, fontSize: 28, fontWeight: 800, color: C.textStrong, letterSpacing: "-0.5px" },
  logoAccent: { color: ACCENT, fontFamily: FONTS.mono, fontWeight: 500, marginRight: 2 },
  logoDim: { color: C.dim, fontWeight: 400 },
  logoCursor: { color: ACCENT, animation: "pulse 1.2s step-end infinite", marginLeft: 2 },
  subtitle: { fontSize: 13.5, color: C.faint, textAlign: "center", maxWidth: 360, lineHeight: 1.65, marginTop: 6 },
  content: { width: "100%", display: "flex", flexDirection: "column", gap: 16, marginTop: 24 },

  card: { ...CARD, borderRadius: 16, padding: 24, background: C.surface1 },
  sectionLabel: { fontFamily: FONTS.mono, fontSize: TEXT.xs, letterSpacing: "1.5px", textTransform: "uppercase", color: C.faint, marginBottom: 18 },

  syncBanner: {
    ...CARD,
    borderRadius: 16,
    padding: "22px",
    width: "100%",
    display: "flex",
    flexDirection: "column",
    gap: 8,
    background: C.surface1,
  },
  syncBannerTitle: { fontSize: 13, fontWeight: 700, color: C.textStrong, letterSpacing: "0.02em" },
  syncBannerText: { fontSize: 13, color: C.muted, lineHeight: 1.5 },
  syncBannerNote: { fontSize: 13, color: C.dim, lineHeight: 1.45 },

  authCard: { ...CARD, borderRadius: 16, padding: "22px", width: "100%" },
  authRow: { display: "flex", alignItems: "center", gap: 12 },
  authCol: { display: "flex", flexDirection: "column", alignItems: "center", gap: 10 },
  authAvatar: { width: 32, height: 32, borderRadius: 999, border: `1px solid ${C.border}` },
  authAvatarFallback: { width: 32, height: 32, borderRadius: 999, background: C.surface2 },
  authText: { display: "flex", flexDirection: "column", gap: 2, flex: 1, minWidth: 0 },
  authName: { fontSize: 14, color: C.textStrong, fontWeight: 700, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  authEmail: { fontSize: 13, color: C.dim, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  authHint: { fontSize: 13, color: C.dim },
  authBtn: { background: "none", border: `1px solid ${C.border}`, borderRadius: 10, padding: "8px 12px", color: C.dim, fontSize: 13, cursor: "pointer", whiteSpace: "nowrap", fontFamily: FONTS.mono },
  authError: { fontSize: 13, color: "var(--danger)", textAlign: "center", maxWidth: 340, lineHeight: 1.45 },

  statsCard: { ...CARD, borderRadius: 16, padding: "24px", width: "100%", display: "flex", flexDirection: "column", gap: 16 },
  statsRow: { display: "flex", justifyContent: "space-between", gap: 8 },
  statBlock: { display: "flex", flexDirection: "column", alignItems: "center", gap: 2, flex: 1 },
  statValue: { fontSize: 28, fontWeight: 700, color: C.textStrong, lineHeight: 1, fontVariantNumeric: "tabular-nums", fontFamily: FONTS.display },
  statLabel2: { fontSize: 13, color: C.dim, textTransform: "uppercase", letterSpacing: "0.08em" },

  weakSection: { borderTop: `1px solid ${C.border}`, paddingTop: 10, display: "flex", flexDirection: "column", gap: 6 },
  weakLabel: { fontSize: 13, color: "var(--danger)", textTransform: "uppercase", letterSpacing: "0.5px" },
  weakList: { display: "flex", flexDirection: "column", gap: 3 },
  weakItem: { fontSize: 13, color: C.muted, lineHeight: 1.35 },

  configCard: { ...CARD, borderRadius: 16, padding: "24px", width: "100%", display: "flex", flexDirection: "column", gap: 18 },
  configRow: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12 },
  configLabel: { fontSize: 13, color: C.faint, minWidth: 86, textTransform: "uppercase", letterSpacing: "1px", fontFamily: FONTS.mono },
  pillGroup: { display: "flex", gap: 10, flexWrap: "wrap", justifyContent: "flex-end" },
  pill: {
    padding: "7px 16px",
    borderRadius: 999,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: C.border,
    background: "transparent",
    color: C.dim,
    fontSize: 13,
    cursor: "pointer",
    transition: "all 0.15s ease",
    fontFamily: FONTS.mono,
    whiteSpace: "nowrap",
  },
  pillSmall: {
    padding: "7px 14px",
    borderRadius: 999,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: C.border,
    background: "transparent",
    color: C.dim,
    fontSize: 13,
    cursor: "pointer",
    transition: "all 0.15s ease",
    fontFamily: FONTS.mono,
    whiteSpace: "nowrap",
  },
  pillActive: { color: ACCENT, borderColor: "var(--accent-ring-soft)", background: "var(--accent-fill-soft)" },

  startBtn: {
    padding: "16px 18px",
    borderRadius: 14,
    border: "none",
    background: "var(--accent)",
    color: "var(--bg-page)",
    fontFamily: FONTS.display,
    fontSize: 16,
    fontWeight: 600,
    letterSpacing: "0.3px",
    cursor: "pointer",
    transition: "filter 0.2s ease, transform 0.2s ease",
    position: "relative",
    overflow: "hidden",
  },
  browseBtn: { padding: "9px 18px", borderRadius: 10, border: `1px solid ${C.border}`, background: C.surface1, color: C.dim, fontSize: 13, cursor: "pointer", fontFamily: FONTS.mono, letterSpacing: "0.2px" },
  menuBtnRow: { display: "flex", gap: 12 },

  resetBtn: { background: "none", border: "none", padding: "6px 12px", color: C.faint, fontSize: 13, cursor: "pointer", fontFamily: FONTS.ui },
  resetConfirm: { display: "flex", alignItems: "center", gap: 10 },

  playContainer: { width: "100%", maxWidth: 720, display: "flex", flexDirection: "column", gap: 24, paddingTop: 20 },
  topBar: { width: "100%", display: "flex", justifyContent: "space-between", alignItems: "center", padding: "16px 0 6px" },
  backBtn: { background: C.surface1, border: `1px solid ${C.border}`, color: C.dim, fontSize: 13, cursor: "pointer", padding: "8px 12px", borderRadius: 10, fontFamily: FONTS.mono, letterSpacing: "0.2px" },
  stats2: { display: "flex", gap: 16, alignItems: "center" },
  statItem: { fontSize: 14, fontWeight: 700, color: C.textStrong, fontFamily: FONTS.display },
  statDim: { color: C.dim, fontWeight: 500 },

  progressTrack: { height: 4, background: C.border, borderRadius: 999, overflow: "hidden" },
  progressBar: { height: "100%", background: ACCENT, borderRadius: 999, transition: "width 0.3s ease" },

  questionArea: { display: "flex", flexDirection: "column", alignItems: "center", gap: 12, padding: "32px 0 16px" },
  diffBadge: { fontSize: 13, fontWeight: 700, padding: "3px 10px", borderRadius: 999, border: "1px solid", textTransform: "uppercase", letterSpacing: "0.6px" },
  questionName: { fontSize: 24, fontWeight: 700, color: C.textStrong, textAlign: "center", lineHeight: 1.25, fontFamily: FONTS.display, letterSpacing: "-0.3px" },

  descToggle: { background: "none", border: "none", color: C.muted, fontSize: 13, cursor: "pointer", display: "flex", alignItems: "center", gap: 8, padding: "6px 10px", borderRadius: 10, transition: "all 0.15s ease" },
  descHotkey: { fontSize: 13, padding: "1px 6px", borderRadius: 6, border: `1px solid ${C.border}`, color: C.dim, fontWeight: 700 },
  descBox: { ...CARD, background: C.surface1, borderRadius: 16, padding: "22px", fontSize: 14, lineHeight: 1.65, color: C.muted, maxWidth: 560, textAlign: "left", overflow: "hidden" },
  questionPrompt: { fontSize: 14, color: C.dim, marginTop: 4 },

  choicesGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 },
  choiceBtn: {
    padding: "16px 14px",
    borderRadius: 16,
    border: `1px solid ${C.border}`,
    background: C.surface1,
    fontSize: 14,
    cursor: "pointer",
    textAlign: "left",
    transition: "all 0.12s ease",
    display: "flex",
    alignItems: "center",
    gap: 10,
    lineHeight: 1.45,
  },
  choiceNum: {
    fontSize: 13,
    color: C.dim,
    fontWeight: 700,
    flexShrink: 0,
    width: 22,
    height: 22,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 7,
    border: `1px solid ${C.border}`,
    background: C.surface2,
    fontVariantNumeric: "tabular-nums",
  },
  choiceState: {
    marginLeft: "auto",
    borderRadius: 999,
    border: `1px solid ${C.border}`,
    padding: "2px 8px",
    fontFamily: FONTS.mono,
    fontSize: 13,
    lineHeight: 1.2,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    whiteSpace: "nowrap",
    flexShrink: 0,
  },

  nextArea: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "16px 0" },
  nextBtn: { padding: "9px 18px", borderRadius: 10, border: `1px solid ${C.border}`, background: C.surface1, color: C.textStrong, fontSize: 13, cursor: "pointer", fontWeight: 700, fontFamily: FONTS.mono },

  resultsContainer: { width: "100%", maxWidth: 720, display: "flex", flexDirection: "column", gap: 24, alignItems: "center", paddingTop: 10 },
  resultsHeader: { display: "flex", flexDirection: "column", alignItems: "center", gap: 16, padding: "24px 0" },
  scoreCircle: { display: "flex", alignItems: "baseline", gap: 2 },
  scoreNum: { fontSize: 56, fontWeight: 800, color: C.textStrong, lineHeight: 1, fontFamily: FONTS.display, letterSpacing: "-0.5px" },
  scorePct: { fontSize: 24, fontWeight: 600, color: C.dim },
  scoreSummary: { fontSize: 15, color: C.muted },
  lifetimeBar: { ...CARD, borderRadius: 14, padding: "10px 14px" },
  lifetimeLabel: { fontSize: 13, color: C.dim, fontFamily: FONTS.mono },

  resultsList: { width: "100%", display: "flex", flexDirection: "column", gap: 6 },
  resultRowOuter: { ...CARD, borderRadius: 14, overflow: "hidden" },
  resultRow: { display: "flex", alignItems: "center", gap: 10, padding: "10px 12px", fontSize: 13, cursor: "pointer", borderRadius: 10, transition: "background 0.1s ease" },
  resultIcon: { fontSize: 14, fontWeight: 900, flexShrink: 0, width: 18 },
  resultOutcome: {
    borderRadius: 999,
    border: `1px solid ${C.border}`,
    padding: "2px 8px",
    fontSize: 13,
    fontWeight: 700,
    fontFamily: FONTS.mono,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    whiteSpace: "nowrap",
    flexShrink: 0,
  },
  resultName: { color: C.text, flex: 1, fontSize: 13, lineHeight: 1.35 },
  resultPattern: { fontSize: 13, fontWeight: 700, flexShrink: 0 },
  resultWrong: { fontSize: 13, color: C.dim, flexShrink: 0 },
  chevron: { fontSize: 13, color: C.faint, flexShrink: 0, marginLeft: 4 },

  resultsActions: { display: "flex", gap: 12, padding: "16px 0" },

  browseContainer: { width: "100%", maxWidth: 920, display: "flex", flexDirection: "column", gap: 24, paddingTop: 20 },
  browseTitle: { fontSize: 20, fontWeight: 800, color: C.textStrong, fontFamily: FONTS.display, letterSpacing: "-0.2px" },
  browseGrid: { display: "grid", gridTemplateColumns: "1fr", gap: 20 },

  patternCard: { ...CARD, borderRadius: 16, padding: "22px" },
  patternHeader: { display: "flex", alignItems: "center", gap: 8, marginBottom: 10 },
  patternDot: { width: 8, height: 8, borderRadius: "50%", flexShrink: 0 },
  patternName: { fontSize: 15, fontWeight: 800, flex: 1, fontFamily: FONTS.display },
  patternCount: { fontSize: 13, color: C.dim, fontWeight: 700, fontFamily: FONTS.mono },

  patternQ: { fontSize: 13, color: C.muted, padding: "7px 8px 7px 16px", display: "flex", alignItems: "center", gap: 8, cursor: "pointer", borderRadius: 10, transition: "background 0.1s ease" },
  patternQDiff: { fontSize: 13, flexShrink: 0 },
  browseDescBox: { padding: "6px 8px 10px 30px", fontSize: 13, lineHeight: 1.6, color: C.dim, overflow: "hidden" },

  // Template styles
  codeBlock: {
    background: "var(--surface-overlay)",
    border: `1px solid ${C.border}`,
    borderRadius: 14,
    padding: "12px 14px",
    fontSize: TEXT.code,
    lineHeight: 1.6,
    color: C.textStrong,
    fontFamily: FONTS.mono,
    width: "100%",
    maxWidth: "100%",
    minWidth: 0,
    boxSizing: "border-box",
    alignSelf: "stretch",
    overflowX: "auto",
    overflowY: "hidden",
    WebkitOverflowScrolling: "touch",
    whiteSpace: "pre",
    margin: "6px 0",
    boxShadow: "inset 0 1px 0 var(--panel-stroke-inner)",
  },
  templateToggle: { background: "none", border: "none", color: C.muted, fontSize: 13, cursor: "pointer", display: "flex", alignItems: "center", gap: 8, padding: "7px 8px", borderRadius: 10, transition: "all 0.15s ease", width: "100%", textAlign: "left" },
  templateToggleLg: { background: "none", border: "none", color: C.muted, fontSize: 13, cursor: "pointer", display: "flex", alignItems: "center", gap: 8, padding: "7px 10px", borderRadius: 10, transition: "all 0.15s ease" },
  templateCount: { fontSize: 13, color: C.faint, marginLeft: "auto" },
  templatePanel: { paddingLeft: 8, overflow: "hidden" },
  templatePanelLg: { ...CARD, borderRadius: 16, padding: "22px", maxWidth: 560, overflow: "hidden" },
  templateSection: { display: "flex", flexDirection: "column", gap: 4, padding: "4px 0" },
  templateItem: { marginBottom: 10 },
  templateName: { fontSize: 13, color: "var(--warn)", fontWeight: 700, marginBottom: 6 },
  templateFullCard: { ...CARD, borderRadius: 16, padding: "22px" },

  // Blueprint mode
  blueprintContainer: { width: "100%", maxWidth: 920, display: "flex", flexDirection: "column", gap: 16, paddingTop: 20 },
  blueprintMenuContainer: { width: "100%", maxWidth: 420, display: "flex", flexDirection: "column", gap: 14, paddingTop: 20, paddingBottom: 128 },
  blueprintTitle: { fontSize: 18, fontWeight: 800, color: C.textStrong, fontFamily: FONTS.display, letterSpacing: "-0.2px" },
  blueprintTopMeta: { fontSize: 13, color: C.dim, fontFamily: FONTS.mono, minWidth: 72, textAlign: "right" },
  blueprintViewPane: { display: "flex", flexDirection: "column", gap: 12, animation: "blueprintViewIn 0.24s ease" },
  blueprintWorldNavBar: {
    width: "100%",
    display: "grid",
    gridTemplateColumns: "auto minmax(0, 1fr) auto",
    alignItems: "center",
    gap: 8,
    padding: "16px 0 4px",
  },
  blueprintWorldNavTitle: {
    fontSize: 14,
    color: C.textStrong,
    fontWeight: 700,
    fontFamily: FONTS.display,
    lineHeight: 1.2,
    textAlign: "center",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  blueprintWorldNavMeta: {
    minWidth: 72,
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    gap: 1,
    fontSize: 13,
    color: C.dim,
    fontFamily: FONTS.mono,
    lineHeight: 1.25,
    fontVariantNumeric: "tabular-nums",
  },
  blueprintMenuIntro: { ...CARD, borderRadius: 14, padding: "14px 16px", fontSize: 13, color: C.muted, lineHeight: 1.55 },
  blueprintMenuList: { display: "grid", gridTemplateColumns: "1fr", gap: 12 },
  blueprintMenuCard: {
    ...CARD,
    borderRadius: 14,
    padding: "16px 18px",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 8,
    textAlign: "left",
    cursor: "pointer",
    transition: "background 0.15s ease",
    touchAction: "manipulation",
  },
  blueprintMenuCardTop: { display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap" },
  blueprintDailyBannerRow: {
    ...CARD,
    borderRadius: 12,
    minHeight: 46,
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    padding: "8px 12px",
    cursor: "pointer",
    textAlign: "left",
    transition: "background 0.2s ease, border-color 0.2s ease, transform 0.2s ease",
  },
  blueprintContinueBtn: {
    borderRadius: 14,
    border: "1px solid",
    minHeight: 56,
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    justifyContent: "center",
    gap: 4,
    padding: "11px 14px",
    color: "var(--bg-page)",
    textAlign: "left",
    cursor: "pointer",
    transition: "filter 0.2s ease, transform 0.2s ease",
  },
  blueprintTrailWrap: { position: "relative", display: "flex", flexDirection: "column" },
  blueprintTrailWrapMobile: { position: "relative", display: "flex", flexDirection: "column", gap: 10 },
  blueprintTrailRow: { position: "relative" },
  blueprintTrailRowMobile: { position: "relative" },
  blueprintTrailSvg: { position: "absolute", inset: 0, width: "100%", height: "100%", pointerEvents: "none" },
  blueprintTrailRailMobile: {
    position: "absolute",
    left: 42,
    top: 78,
    bottom: -10,
    borderLeftWidth: 1.5,
    borderLeftStyle: "solid",
    borderLeftColor: C.borderStrong,
    pointerEvents: "none",
  },
  blueprintWorldNode: {
    ...CARD,
    position: "absolute",
    top: 6,
    width: "min(220px, 86vw)",
    minHeight: 82,
    borderRadius: 14,
    display: "flex",
    alignItems: "center",
    gap: 11,
    padding: "8px 10px",
    textAlign: "left",
    cursor: "pointer",
    transition: "background 0.2s ease, border-color 0.2s ease, transform 0.2s ease, opacity 0.2s ease",
  },
  blueprintWorldNodeMobile: {
    ...CARD,
    position: "relative",
    width: "100%",
    minHeight: 82,
    borderRadius: 14,
    display: "flex",
    alignItems: "center",
    gap: 11,
    padding: "8px 10px",
    textAlign: "left",
    cursor: "pointer",
    transition: "background 0.2s ease, border-color 0.2s ease, transform 0.2s ease, opacity 0.2s ease",
  },
  blueprintNodeBadge: {
    width: 24,
    height: 24,
    borderRadius: 999,
    border: `1px solid ${C.border}`,
    background: C.surface2,
    color: C.dim,
    fontSize: 13,
    fontFamily: FONTS.mono,
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    textTransform: "uppercase",
  },
  blueprintNodeTitle: { fontSize: 16, color: C.textStrong, fontWeight: 700, fontFamily: FONTS.display, letterSpacing: "-0.2px" },
  blueprintNodeMeta: { fontSize: 13, color: C.dim, lineHeight: 1.4, fontFamily: FONTS.mono },
  blueprintTierCard: { ...CARD, borderRadius: 14, display: "flex", flexDirection: "column", gap: 2 },
  blueprintTierHeader: {
    width: "100%",
    background: "none",
    border: "none",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
    padding: "12px 14px",
    textAlign: "left",
    minHeight: 44,
  },
  blueprintProblemRow: {
    ...CARD,
    borderRadius: 10,
    minHeight: 44,
    width: "100%",
    padding: "9px 10px",
    display: "flex",
    alignItems: "center",
    gap: 9,
    textAlign: "left",
    transition: "background 0.2s ease, border-color 0.2s ease, transform 0.2s ease",
  },
  blueprintDailyStartBtn: {
    marginTop: 4,
    width: "100%",
    minHeight: 44,
    borderRadius: 12,
    border: "1px solid var(--warn-ring-soft)",
    color: "var(--bg-page)",
    fontFamily: FONTS.display,
    fontSize: 15,
    fontWeight: 700,
    cursor: "pointer",
    transition: "filter 0.2s ease, transform 0.2s ease",
  },
  blueprintTabFade: {
    position: "fixed",
    left: "50%",
    transform: "translateX(-50%)",
    bottom: 64,
    width: "min(420px, calc(100vw - 32px))",
    height: 56,
    background: "linear-gradient(180deg, transparent, var(--surface-overlay-strong))",
    pointerEvents: "none",
    zIndex: 20,
  },
  blueprintTabBar: {
    ...CARD,
    position: "fixed",
    left: "50%",
    transform: "translateX(-50%)",
    bottom: 16,
    width: "min(420px, calc(100vw - 32px))",
    borderRadius: 14,
    padding: 6,
    display: "grid",
    gridTemplateColumns: "1fr 1fr 1fr",
    gap: 6,
    zIndex: 21,
  },
  blueprintTabBtn: {
    minHeight: 44,
    borderRadius: 10,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "transparent",
    background: "transparent",
    color: C.dim,
    fontSize: 13,
    fontFamily: FONTS.mono,
    cursor: "pointer",
    transition: "background 0.2s ease, border-color 0.2s ease, color 0.2s ease, transform 0.2s ease",
  },
  blueprintTabBtnActive: { color: C.textStrong, borderColor: C.borderStrong, background: C.surface2 },
  blueprintPatternBadge: {
    fontSize: 13,
    fontFamily: FONTS.mono,
    color: C.dim,
    border: `1px solid ${C.border}`,
    background: C.surface2,
    borderRadius: 999,
    padding: "3px 8px",
  },
  blueprintLevelTitle: { fontSize: 17, color: C.textStrong, fontWeight: 700, fontFamily: FONTS.display, letterSpacing: "-0.2px" },
  blueprintLevelDesc: { fontSize: 13, color: C.muted, lineHeight: 1.5 },
  blueprintStarRow: { display: "flex", gap: 6, marginTop: 2, justifyContent: "center", width: "100%" },
  blueprintStar: { fontFamily: FONTS.mono, fontWeight: 700, fontSize: 14 },

  blueprintProblemCard: { ...CARD, borderRadius: 14, padding: "16px 18px", display: "flex", flexDirection: "column", gap: 10 },
  blueprintProblemText: { fontSize: 14, color: C.muted, lineHeight: 1.6 },
  blueprintExample: {
    margin: 0,
    padding: "8px 10px",
    borderRadius: 10,
    border: `1px solid ${C.border}`,
    background: C.surface2,
    color: C.textStrong,
    fontFamily: FONTS.mono,
    fontSize: TEXT.code,
    whiteSpace: "pre-wrap",
    lineHeight: 1.6,
  },

  blueprintStatsStrip: {
    ...CARD,
    borderRadius: 14,
    padding: "10px 12px",
    display: "flex",
    flexWrap: "wrap",
    gap: 12,
    alignItems: "center",
  },
  blueprintStatsItem: { fontSize: 13, color: C.dim, fontFamily: FONTS.mono, letterSpacing: "0.02em" },
  blueprintTapHintBar: {
    ...CARD,
    borderRadius: 10,
    padding: "7px 10px",
    fontSize: 13,
    color: C.dim,
    lineHeight: 1.4,
    background: "var(--accent-fill-soft)",
    borderColor: "var(--accent-ring-soft)",
  },
  blueprintHeaderProgressWrap: {
    minWidth: 160,
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  blueprintHeaderProgressTrack: {
    height: 7,
    width: "100%",
    borderRadius: 999,
    background: "var(--surface-soft)",
    overflow: "hidden",
  },
  blueprintHeaderProgressFill: {
    height: "100%",
    borderRadius: 999,
    background: "linear-gradient(90deg, var(--accent) 0%, var(--accent2) 100%)",
    transition: "width 0.24s ease",
  },
  blueprintHeaderProgressLabel: {
    fontSize: 13,
    color: C.faint,
    fontFamily: FONTS.mono,
    letterSpacing: "0.03em",
  },

  blueprintBuildBoard: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 38fr) minmax(0, 62fr)",
    gap: 12,
    alignItems: "stretch",
    minHeight: "58vh",
    maxHeight: "66vh",
  },
  blueprintTrayPane: {
    ...CARD,
    borderRadius: 14,
    padding: 10,
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    gap: 8,
    overflow: "hidden",
  },
  blueprintPaneSlots: {
    ...CARD,
    borderRadius: 14,
    padding: 10,
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    gap: 8,
    overflow: "hidden",
  },
  blueprintPaneHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    padding: "2px 2px 6px",
  },
  blueprintDeckLabel: { fontSize: 13, color: C.faint, textTransform: "uppercase", letterSpacing: "0.11em", fontFamily: FONTS.mono },
  blueprintTrayList: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    paddingRight: 2,
    display: "flex",
    flexDirection: "column",
    gap: 8,
    WebkitOverflowScrolling: "touch",
  },
  blueprintTrayCard: {
    ...CARD,
    borderRadius: 10,
    padding: 0,
    width: "100%",
    flexShrink: 0,
    position: "relative",
    overflow: "hidden",
    textAlign: "left",
    transition: "border-color 0.15s ease, background 0.15s ease, opacity 0.15s ease",
  },
  blueprintTrayCardInner: {
    padding: "10px 30px 10px 10px",
    display: "flex",
    flexDirection: "column",
    gap: 8,
    width: "100%",
    minHeight: "100%",
  },
  blueprintTrayPlacedBadge: {
    position: "absolute",
    top: 8,
    right: 8,
    borderRadius: 999,
    border: `1px solid var(--accent-ring-mid)`,
    background: "var(--accent-fill-mid)",
    color: "var(--accent)",
    fontFamily: FONTS.mono,
    fontSize: 13,
    lineHeight: 1,
    padding: "4px 7px",
    textTransform: "uppercase",
    letterSpacing: "0.03em",
  },

  blueprintSlotList: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: 10,
    paddingRight: 2,
    WebkitOverflowScrolling: "touch",
  },
  blueprintSectionCard: {
    ...CARD,
    borderRadius: 12,
    padding: "10px",
    display: "flex",
    flexDirection: "column",
    gap: 8,
    transition: "background 0.18s ease, border-color 0.18s ease, box-shadow 0.18s ease",
  },
  blueprintSectionHeader: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  blueprintSectionMeta: {
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: 2,
    flex: 1,
  },
  blueprintSlotIcon: {
    fontSize: 13,
    width: 22,
    height: 22,
    borderRadius: 999,
    border: `1px solid ${C.border}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: FONTS.mono,
    fontWeight: 700,
  },
  blueprintSlotName: { fontSize: 13, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.09em", fontFamily: FONTS.mono, flexShrink: 0 },
  blueprintSlotDesc: { fontSize: 13, color: C.faint, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  blueprintSlotLimit: {
    minWidth: 22,
    height: 22,
    borderRadius: 999,
    border: `1px solid ${C.border}`,
    fontSize: 13,
    color: C.dim,
    fontFamily: FONTS.mono,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  blueprintSectionSlots: {
    display: "flex",
    flexDirection: "column",
    gap: 7,
  },
  blueprintSectionPlacedCard: {
    ...CARD,
    borderRadius: 9,
    padding: "8px 8px 7px",
    background: C.surface2,
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  blueprintPlacedActions: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  blueprintInlineUndoBtn: {
    width: 20,
    height: 20,
    borderRadius: 999,
    border: `1px solid ${C.border}`,
    background: C.surface1,
    color: C.faint,
    fontFamily: FONTS.mono,
    fontSize: 13,
    lineHeight: 1,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    padding: 0,
    flexShrink: 0,
  },
  blueprintSectionPlaceholder: {
    borderRadius: 9,
    border: `1px dashed ${C.borderStrong}`,
    background: "var(--surface-1)",
    minHeight: 36,
  },
  blueprintCardCode: {
    margin: 0,
    whiteSpace: "pre-wrap",
    fontSize: TEXT.code,
    lineHeight: 1.6,
    color: C.text,
    fontFamily: FONTS.mono,
    textAlign: "left",
  },
  actionBar: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8, marginTop: 8 },
  blueprintHintBtn: {
    position: "absolute",
    top: 6,
    right: 6,
    border: `1px solid ${C.border}`,
    background: C.surface2,
    color: C.dim,
    width: 22,
    height: 22,
    borderRadius: 999,
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: FONTS.mono,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },
  blueprintHintBubble: { marginTop: 8, fontSize: 13, color: C.dim, lineHeight: 1.45, background: C.surface2, border: `1px solid ${C.border}`, borderRadius: 8, padding: "6px 8px" },
  blueprintDependencyWarning: {
    ...CARD,
    borderRadius: 10,
    marginTop: 6,
    padding: "7px 9px",
    fontSize: 13,
    lineHeight: 1.4,
    color: "var(--warn)",
    borderColor: "var(--warn-ring-soft)",
    background: "var(--warn-fill-mid)",
  },
  blueprintFeedbackBadge: {
    marginLeft: 6,
    borderRadius: 999,
    border: `1px solid ${C.border}`,
    padding: "2px 6px",
    fontFamily: FONTS.mono,
    fontSize: 13,
    lineHeight: 1.2,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    whiteSpace: "nowrap",
    flexShrink: 0,
  },
  blueprintCompletionScrim: {
    position: "fixed",
    inset: 0,
    background: "var(--surface-overlay-strong)",
    zIndex: 1300,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
  },
  blueprintCompletionCard: {
    ...CARD,
    width: "min(360px, 100%)",
    borderRadius: 14,
    padding: "18px 16px",
    display: "flex",
    flexDirection: "column",
    gap: 10,
    alignItems: "center",
    textAlign: "center",
  },
  blueprintCompletionActions: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginTop: 2,
  },

  blueprintSheetScrim: {
    position: "fixed",
    inset: 0,
    background: "var(--surface-overlay)",
    zIndex: 1210,
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "center",
    padding: "12px 10px calc(env(safe-area-inset-bottom, 0px) + 10px)",
  },
  blueprintSheet: {
    ...CARD,
    width: "100%",
    maxWidth: 920,
    borderRadius: 14,
    maxHeight: "72vh",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    background: C.surface1,
  },
  blueprintSheetHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
    padding: "10px 12px",
    borderBottom: `1px solid ${C.border}`,
  },
  blueprintSheetClose: {
    width: 36,
    height: 36,
    borderRadius: 10,
    border: `1px solid ${C.border}`,
    background: C.surface2,
    color: C.dim,
    fontFamily: FONTS.mono,
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  blueprintSheetList: {
    padding: "10px 12px 12px",
    display: "flex",
    flexDirection: "column",
    gap: 8,
    overflowY: "auto",
    maxHeight: "calc(72vh - 58px)",
  },
  blueprintSheetCard: {
    ...CARD,
    borderRadius: 10,
    padding: "10px",
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  blueprintSheetActions: { display: "flex", gap: 6, flexWrap: "wrap", justifyContent: "flex-end" },

  blueprintExecutionWrap: { display: "flex", flexDirection: "column", gap: 12, paddingBottom: 24 },
  blueprintExecCard: { ...CARD, borderRadius: 14, padding: "14px 12px" },
  execHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 8, marginBottom: 10 },
  execLabel: {
    fontSize: 13,
    color: C.faint,
    textTransform: "uppercase",
    letterSpacing: "0.1em",
    fontFamily: FONTS.mono,
    fontWeight: 700,
  },
  phasePill: {
    borderRadius: 999,
    border: `1px solid ${C.border}`,
    padding: "3px 9px",
    fontSize: 13,
    lineHeight: 1.15,
    textTransform: "uppercase",
    letterSpacing: "0.07em",
    fontFamily: FONTS.mono,
    fontWeight: 700,
  },
  execCard: {
    ...CARD,
    borderRadius: 10,
    padding: "8px 10px",
    background: C.surface2,
  },
  blueprintPhaseRow: { display: "flex", alignItems: "center", gap: 8, marginBottom: 10 },
  blueprintArrayRow: { display: "flex", gap: 6, flexWrap: "wrap", marginBottom: 10, justifyContent: "center" },
  blueprintArrayCellWrap: { display: "flex", flexDirection: "column", alignItems: "center", gap: 2 },
  blueprintArrayCell: {
    width: 36,
    height: 36,
    borderRadius: 8,
    border: `1px solid ${C.border}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: FONTS.mono,
    fontSize: 13,
    color: C.textStrong,
    transition: "all 0.15s ease",
  },
  blueprintArrayMarker: { fontSize: 13, color: C.faint, minHeight: 14, fontFamily: FONTS.mono },
  stateBox: {
    ...CARD,
    borderRadius: 10,
    padding: "10px",
    background: C.surface2,
  },
  blueprintStateLabel: { fontSize: 13, color: C.dim, marginBottom: 6, fontWeight: 700, letterSpacing: "0.08em", textTransform: "uppercase", fontFamily: FONTS.mono },
  blueprintStateVars: { display: "flex", flexWrap: "wrap", gap: 8 },
  stateVar: {
    borderRadius: 8,
    border: `1px solid ${C.border}`,
    background: C.surface1,
    padding: "4px 8px",
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontFamily: FONTS.mono,
    fontSize: 13,
    maxWidth: "100%",
  },
  blueprintResultPill: { marginTop: 10, padding: "8px 10px", borderRadius: 8, border: "1px solid var(--accent-ring-soft)", background: "var(--accent-fill-soft)", color: "var(--accent)", fontFamily: FONTS.mono, fontSize: 13 },
  stepControls: {
    marginTop: 12,
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: 8,
  },
  stepBtn: {
    minHeight: 36,
    borderRadius: 9,
    border: `1px solid ${C.border}`,
    background: C.surface2,
    color: C.text,
    fontFamily: FONTS.mono,
    fontSize: 13,
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    cursor: "pointer",
  },
  resultsPanel: {
    ...CARD,
    borderRadius: 14,
    padding: "12px",
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  testRow: {
    borderLeftWidth: 3,
    borderLeftStyle: "solid",
    borderLeftColor: C.borderStrong,
    borderRadius: 10,
    border: `1px solid ${C.border}`,
    background: C.surface2,
    padding: "8px 9px",
  },
  blueprintTestBody: { flex: 1, fontFamily: FONTS.mono, fontSize: TEXT.code, lineHeight: 1.6, display: "flex", flexDirection: "column", gap: 2 },
  blueprintTestLine: {
    color: C.muted,
    lineHeight: 1.45,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    overflowWrap: "anywhere",
  },
  feedbackBox: {
    ...CARD,
    borderRadius: 12,
    padding: "12px",
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  blueprintFeedbackText: { fontSize: 13, color: C.muted, lineHeight: 1.55, margin: 0 },

  hotkeyRow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 8,
  },
  hotkeyChip: {
    borderRadius: 999,
    border: `1px solid ${C.border}`,
    background: C.surface1,
    color: C.dim,
    fontFamily: FONTS.mono,
    fontSize: 13,
    lineHeight: 1.2,
    letterSpacing: "0.02em",
    padding: "4px 8px",
    whiteSpace: "nowrap",
  },

  tutorialLayer: {
    position: "fixed",
    inset: 0,
    zIndex: 2400,
    pointerEvents: "none",
  },
  tutorialBackdrop: {
    position: "fixed",
    inset: 0,
    background: "var(--surface-overlay-strong)",
    pointerEvents: "none",
  },
  tutorialSpotlight: {
    position: "fixed",
    borderRadius: 12,
    border: "1px solid var(--accent-ring-strong)",
    boxShadow: "0 0 0 9999px var(--surface-overlay-strong)",
    pointerEvents: "none",
  },
  tutorialTooltipWrap: {
    position: "fixed",
    pointerEvents: "auto",
  },
  tutorialTooltip: {
    ...CARD,
    position: "relative",
    borderRadius: 14,
    padding: "14px 14px 12px",
    background: C.surface1,
    display: "flex",
    flexDirection: "column",
    gap: 8,
    boxShadow: "var(--shadow)",
  },
  tutorialTooltipArrow: {
    position: "absolute",
    width: 10,
    height: 10,
    borderTop: `1px solid ${C.border}`,
    borderLeft: `1px solid ${C.border}`,
    background: C.surface1,
  },
  tutorialTooltipTitle: {
    color: C.textStrong,
    fontSize: 14,
    fontWeight: 700,
    fontFamily: FONTS.display,
  },
  tutorialTooltipBody: {
    color: C.muted,
    fontSize: 13,
    lineHeight: 1.45,
  },
  tutorialTooltipMeta: {
    fontSize: 13,
    color: C.faint,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    fontFamily: FONTS.mono,
  },
  tutorialTooltipActions: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  tutorialTooltipGhostBtn: {
    borderRadius: 9,
    border: `1px solid ${C.border}`,
    background: C.surface2,
    color: C.dim,
    fontSize: 13,
    padding: "6px 9px",
    fontFamily: FONTS.mono,
    cursor: "pointer",
  },
  tutorialTooltipNextBtn: {
    marginLeft: "auto",
    borderRadius: 9,
    border: "1px solid var(--accent-ring-mid)",
    background: "var(--accent-fill-strong)",
    color: "var(--accent)",
    fontSize: 13,
    padding: "6px 11px",
    fontFamily: FONTS.mono,
    fontWeight: 700,
    cursor: "pointer",
  },
  tutorialLiveRegion: {
    position: "absolute",
    width: 1,
    height: 1,
    overflow: "hidden",
    clip: "rect(1px, 1px, 1px, 1px)",
    whiteSpace: "nowrap",
  },
  tutorialTip: {
    ...CARD,
    borderRadius: 12,
    padding: "10px 11px",
    background: "var(--surface-overlay-strong)",
    borderColor: "var(--accent-ring-soft)",
    boxShadow: "var(--shadow-soft)",
    display: "flex",
    flexDirection: "column",
    gap: 4,
    cursor: "pointer",
  },
  tutorialTipTitle: {
    color: C.textStrong,
    fontSize: 13,
    fontWeight: 700,
  },
  tutorialTipBody: {
    color: C.muted,
    fontSize: 13,
    lineHeight: 1.4,
  },
  tutorialTipHint: {
    marginTop: 2,
    fontSize: 13,
    color: C.faint,
    fontFamily: FONTS.mono,
  },
};
