const FONTS = {
  ui: "'DM Sans', system-ui, -apple-system, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
  mono: "'DM Mono', ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
  display: "'Outfit', 'DM Sans', system-ui, -apple-system, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
};

const C = {
  bg: "var(--bg-app)",
  surface1: "var(--surface-1)",
  surface2: "var(--surface-2)",
  border: "var(--border)",
  borderStrong: "var(--border-strong)",
  text: "var(--text)",
  textStrong: "var(--text-strong)",
  muted: "var(--muted)",
  dim: "var(--dim)",
  faint: "var(--faint)",
};

const ACCENT = "var(--accent)";
const CARD_BG = C.surface1;
const CARD = {
  background: CARD_BG,
  border: `1px solid ${C.border}`,
  boxShadow: "var(--shadow-soft)",
};

export const S = {
  root: {
    minHeight: "100vh",
    width: "100%",
    color: C.text,
    fontFamily: FONTS.ui,
    fontSize: 15,
    lineHeight: 1.55,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "0 16px 48px",
    animation: "fadeIn 0.4s ease",
  },

  menuContainer: { width: "100%", maxWidth: 520, display: "flex", flexDirection: "column", gap: 16 },
  menuTopbar: { width: "100%", display: "flex", justifyContent: "space-between", alignItems: "center", padding: "20px 0 16px", animation: "fadeSlideIn 0.4s ease both" },
  menuUserInfo: { display: "flex", alignItems: "center", gap: 10, minWidth: 0 },
  menuAvatar: {
    width: 32,
    height: 32,
    borderRadius: 999,
    background: "linear-gradient(135deg, var(--accent), var(--info))",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: FONTS.display,
    fontWeight: 700,
    fontSize: 14,
    color: "white",
    flexShrink: 0,
  },
  menuUsername: { fontFamily: FONTS.ui, fontSize: 14, color: C.muted, fontWeight: 500, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  menuSignout: { fontFamily: FONTS.mono, fontSize: 11, color: C.faint, background: "none", border: `1px solid ${C.border}`, borderRadius: 8, padding: "6px 12px", cursor: "pointer" },

  brand: { textAlign: "center", padding: "20px 0 8px", animation: "fadeSlideIn 0.4s ease 0.1s both" },
  logo: { fontFamily: FONTS.display, fontSize: 28, fontWeight: 800, color: C.textStrong, letterSpacing: "-0.5px" },
  logoAccent: { color: ACCENT, fontFamily: FONTS.mono, fontWeight: 500, marginRight: 2 },
  logoDim: { color: C.dim, fontWeight: 400 },
  logoCursor: { color: ACCENT, animation: "pulse 1.2s step-end infinite", marginLeft: 2 },
  subtitle: { fontSize: 13.5, color: C.faint, textAlign: "center", maxWidth: 360, lineHeight: 1.65, marginTop: 6 },
  content: { width: "100%", display: "flex", flexDirection: "column", gap: 16, marginTop: 24 },

  card: { ...CARD, borderRadius: 16, padding: 24, background: C.surface1 },
  sectionLabel: { fontFamily: FONTS.mono, fontSize: 10, letterSpacing: "1.5px", textTransform: "uppercase", color: C.faint, marginBottom: 18 },

  syncBanner: {
    ...CARD,
    borderRadius: 16,
    padding: "22px",
    width: "100%",
    display: "flex",
    flexDirection: "column",
    gap: 8,
    background: C.surface1,
    border: `1px solid ${C.border}`,
  },
  syncBannerTitle: { fontSize: 13, fontWeight: 700, color: C.textStrong, letterSpacing: "0.02em" },
  syncBannerText: { fontSize: 13, color: C.muted, lineHeight: 1.5 },
  syncBannerNote: { fontSize: 12, color: C.dim, lineHeight: 1.45 },

  authCard: { ...CARD, borderRadius: 16, padding: "22px", width: "100%" },
  authRow: { display: "flex", alignItems: "center", gap: 12 },
  authCol: { display: "flex", flexDirection: "column", alignItems: "center", gap: 10 },
  authAvatar: { width: 32, height: 32, borderRadius: 999, border: `1px solid ${C.border}` },
  authAvatarFallback: { width: 32, height: 32, borderRadius: 999, background: C.surface2 },
  authText: { display: "flex", flexDirection: "column", gap: 2, flex: 1, minWidth: 0 },
  authName: { fontSize: 14, color: C.textStrong, fontWeight: 700, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  authEmail: { fontSize: 12, color: C.dim, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  authHint: { fontSize: 13, color: C.dim },
  authBtn: { background: "none", border: `1px solid ${C.border}`, borderRadius: 10, padding: "8px 12px", color: C.dim, fontSize: 12, cursor: "pointer", whiteSpace: "nowrap", fontFamily: FONTS.mono },
  authError: { fontSize: 12, color: "var(--danger)", textAlign: "center", maxWidth: 340, lineHeight: 1.45 },

  statsCard: { ...CARD, borderRadius: 16, padding: "24px", width: "100%", display: "flex", flexDirection: "column", gap: 16 },
  statsRow: { display: "flex", justifyContent: "space-between", gap: 8 },
  statBlock: { display: "flex", flexDirection: "column", alignItems: "center", gap: 2, flex: 1 },
  statValue: { fontSize: 28, fontWeight: 700, color: C.textStrong, lineHeight: 1, fontVariantNumeric: "tabular-nums", fontFamily: FONTS.display },
  statLabel2: { fontSize: 12, color: C.dim, textTransform: "uppercase", letterSpacing: "0.08em" },

  weakSection: { borderTop: `1px solid ${C.border}`, paddingTop: 10, display: "flex", flexDirection: "column", gap: 6 },
  weakLabel: { fontSize: 11, color: "var(--danger)", textTransform: "uppercase", letterSpacing: "0.5px" },
  weakList: { display: "flex", flexDirection: "column", gap: 3 },
  weakItem: { fontSize: 13, color: C.muted, lineHeight: 1.35 },

  configCard: { ...CARD, borderRadius: 16, padding: "24px", width: "100%", display: "flex", flexDirection: "column", gap: 18 },
  configRow: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12 },
  configLabel: { fontSize: 11, color: C.faint, minWidth: 86, textTransform: "uppercase", letterSpacing: "1px", fontFamily: FONTS.mono },
  pillGroup: { display: "flex", gap: 10, flexWrap: "wrap", justifyContent: "flex-end" },
  pill: {
    padding: "7px 16px",
    borderRadius: 999,
    border: `1px solid ${C.border}`,
    background: "transparent",
    color: C.dim,
    fontSize: 12.5,
    cursor: "pointer",
    transition: "all 0.15s ease",
    fontFamily: FONTS.mono,
    whiteSpace: "nowrap",
  },
  pillSmall: {
    padding: "7px 14px",
    borderRadius: 999,
    border: `1px solid ${C.border}`,
    background: "transparent",
    color: C.dim,
    fontSize: 12,
    cursor: "pointer",
    transition: "all 0.15s ease",
    fontFamily: FONTS.mono,
    whiteSpace: "nowrap",
  },
  pillActive: { color: ACCENT, borderColor: "rgba(16, 185, 129, 0.3)", background: "rgba(16, 185, 129, 0.1)" },

  startBtn: {
    padding: "16px 18px",
    borderRadius: 14,
    border: "none",
    background: "#86efac",
    color: "#0f1117",
    fontFamily: FONTS.display,
    fontSize: 16,
    fontWeight: 600,
    letterSpacing: "0.3px",
    cursor: "pointer",
    transition: "filter 0.2s ease, transform 0.2s ease",
    position: "relative",
    overflow: "hidden",
  },
  browseBtn: { padding: "9px 18px", borderRadius: 10, border: `1px solid ${C.border}`, background: C.surface1, color: C.dim, fontSize: 12, cursor: "pointer", fontFamily: FONTS.mono, letterSpacing: "0.2px" },
  menuBtnRow: { display: "flex", gap: 12 },

  resetBtn: { background: "none", border: "none", padding: "6px 12px", color: C.faint, fontSize: 11, cursor: "pointer", fontFamily: FONTS.ui },
  resetConfirm: { display: "flex", alignItems: "center", gap: 10 },

  playContainer: { width: "100%", maxWidth: 720, display: "flex", flexDirection: "column", gap: 24, paddingTop: 20 },
  topBar: { width: "100%", display: "flex", justifyContent: "space-between", alignItems: "center", padding: "16px 0 6px" },
  backBtn: { background: C.surface1, border: `1px solid ${C.border}`, color: C.dim, fontSize: 12, cursor: "pointer", padding: "8px 12px", borderRadius: 10, fontFamily: FONTS.mono, letterSpacing: "0.2px" },
  stats2: { display: "flex", gap: 16, alignItems: "center" },
  statItem: { fontSize: 14, fontWeight: 700, color: C.textStrong, fontFamily: FONTS.display },
  statDim: { color: C.dim, fontWeight: 500 },

  progressTrack: { height: 4, background: C.border, borderRadius: 999, overflow: "hidden" },
  progressBar: { height: "100%", background: ACCENT, borderRadius: 999, transition: "width 0.3s ease" },

  questionArea: { display: "flex", flexDirection: "column", alignItems: "center", gap: 12, padding: "32px 0 16px" },
  diffBadge: { fontSize: 11, fontWeight: 700, padding: "3px 10px", borderRadius: 999, border: "1px solid", textTransform: "uppercase", letterSpacing: "0.6px" },
  questionName: { fontSize: 24, fontWeight: 700, color: C.textStrong, textAlign: "center", lineHeight: 1.25, fontFamily: FONTS.display, letterSpacing: "-0.3px" },

  descToggle: { background: "none", border: "none", color: C.muted, fontSize: 13, cursor: "pointer", display: "flex", alignItems: "center", gap: 8, padding: "6px 10px", borderRadius: 10, transition: "all 0.15s ease" },
  descHotkey: { fontSize: 11, padding: "1px 6px", borderRadius: 6, border: `1px solid ${C.border}`, color: C.dim, fontWeight: 700 },
  descBox: { ...CARD, background: C.surface1, borderRadius: 16, padding: "22px", fontSize: 14, lineHeight: 1.65, color: C.muted, maxWidth: 560, textAlign: "left", overflow: "hidden" },
  questionPrompt: { fontSize: 14, color: C.dim, marginTop: 4 },

  choicesGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 },
  choiceBtn: {
    padding: "16px 14px",
    borderRadius: 16,
    border: `1px solid ${C.border}`,
    background: C.surface1,
    fontSize: 14,
    cursor: "pointer",
    textAlign: "left",
    transition: "all 0.12s ease",
    display: "flex",
    alignItems: "center",
    gap: 10,
    lineHeight: 1.45,
  },
  choiceNum: {
    fontSize: 12,
    color: C.dim,
    fontWeight: 700,
    flexShrink: 0,
    width: 22,
    height: 22,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 7,
    border: `1px solid ${C.border}`,
    background: C.surface2,
    fontVariantNumeric: "tabular-nums",
  },

  nextArea: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "16px 0" },
  nextBtn: { padding: "9px 18px", borderRadius: 10, border: `1px solid ${C.border}`, background: C.surface1, color: C.textStrong, fontSize: 12, cursor: "pointer", fontWeight: 700, fontFamily: FONTS.mono },

  resultsContainer: { width: "100%", maxWidth: 720, display: "flex", flexDirection: "column", gap: 24, alignItems: "center", paddingTop: 10 },
  resultsHeader: { display: "flex", flexDirection: "column", alignItems: "center", gap: 16, padding: "24px 0" },
  scoreCircle: { display: "flex", alignItems: "baseline", gap: 2 },
  scoreNum: { fontSize: 56, fontWeight: 800, color: C.textStrong, lineHeight: 1, fontFamily: FONTS.display, letterSpacing: "-0.5px" },
  scorePct: { fontSize: 24, fontWeight: 600, color: C.dim },
  scoreSummary: { fontSize: 15, color: C.muted },
  lifetimeBar: { ...CARD, borderRadius: 14, padding: "10px 14px" },
  lifetimeLabel: { fontSize: 12, color: C.dim, fontFamily: FONTS.mono },

  resultsList: { width: "100%", display: "flex", flexDirection: "column", gap: 6 },
  resultRowOuter: { ...CARD, borderRadius: 14, overflow: "hidden" },
  resultRow: { display: "flex", alignItems: "center", gap: 10, padding: "10px 12px", fontSize: 13, cursor: "pointer", borderRadius: 10, transition: "background 0.1s ease" },
  resultIcon: { fontSize: 14, fontWeight: 900, flexShrink: 0, width: 18 },
  resultName: { color: C.text, flex: 1, fontSize: 13, lineHeight: 1.35 },
  resultPattern: { fontSize: 13, fontWeight: 700, flexShrink: 0 },
  resultWrong: { fontSize: 12, color: C.dim, flexShrink: 0 },
  chevron: { fontSize: 11, color: C.faint, flexShrink: 0, marginLeft: 4 },

  resultsActions: { display: "flex", gap: 12, padding: "16px 0" },

  browseContainer: { width: "100%", maxWidth: 920, display: "flex", flexDirection: "column", gap: 24, paddingTop: 20 },
  browseTitle: { fontSize: 20, fontWeight: 800, color: C.textStrong, fontFamily: FONTS.display, letterSpacing: "-0.2px" },
  browseGrid: { display: "grid", gridTemplateColumns: "1fr", gap: 20 },

  patternCard: { ...CARD, borderRadius: 16, padding: "22px" },
  patternHeader: { display: "flex", alignItems: "center", gap: 8, marginBottom: 10 },
  patternDot: { width: 8, height: 8, borderRadius: "50%", flexShrink: 0 },
  patternName: { fontSize: 15, fontWeight: 800, flex: 1, fontFamily: FONTS.display },
  patternCount: { fontSize: 12, color: C.dim, fontWeight: 700, fontFamily: FONTS.mono },

  patternQ: { fontSize: 13, color: C.muted, padding: "7px 8px 7px 16px", display: "flex", alignItems: "center", gap: 8, cursor: "pointer", borderRadius: 10, transition: "background 0.1s ease" },
  patternQDiff: { fontSize: 9, flexShrink: 0 },
  browseDescBox: { padding: "6px 8px 10px 30px", fontSize: 12, lineHeight: 1.6, color: C.dim, overflow: "hidden" },

  // Template styles
  codeBlock: {
    background: "rgba(0,0,0,0.22)",
    border: `1px solid ${C.border}`,
    borderRadius: 14,
    padding: "12px 14px",
    fontSize: 13,
    lineHeight: 1.6,
    color: C.textStrong,
    fontFamily: FONTS.mono,
    overflowX: "auto",
    whiteSpace: "pre",
    margin: "6px 0",
    boxShadow: "inset 0 1px 0 rgba(255,255,255,0.06)",
  },
  templateToggle: { background: "none", border: "none", color: C.muted, fontSize: 13, cursor: "pointer", display: "flex", alignItems: "center", gap: 8, padding: "7px 8px", borderRadius: 10, transition: "all 0.15s ease", width: "100%", textAlign: "left" },
  templateToggleLg: { background: "none", border: "none", color: C.muted, fontSize: 13, cursor: "pointer", display: "flex", alignItems: "center", gap: 8, padding: "7px 10px", borderRadius: 10, transition: "all 0.15s ease" },
  templateCount: { fontSize: 11, color: C.faint, marginLeft: "auto" },
  templatePanel: { paddingLeft: 8, overflow: "hidden" },
  templatePanelLg: { ...CARD, borderRadius: 16, padding: "22px", maxWidth: 560, overflow: "hidden" },
  templateSection: { display: "flex", flexDirection: "column", gap: 4, padding: "4px 0" },
  templateItem: { marginBottom: 10 },
  templateName: { fontSize: 13, color: "#e5c07b", fontWeight: 700, marginBottom: 6 },
  templateFullCard: { ...CARD, borderRadius: 16, padding: "22px" },

  // Blueprint mode
  blueprintContainer: { width: "100%", maxWidth: 920, display: "flex", flexDirection: "column", gap: 16, paddingTop: 20 },
  blueprintMenuContainer: { width: "100%", maxWidth: 420, display: "flex", flexDirection: "column", gap: 14, paddingTop: 20, paddingBottom: 128 },
  blueprintTitle: { fontSize: 18, fontWeight: 800, color: C.textStrong, fontFamily: FONTS.display, letterSpacing: "-0.2px" },
  blueprintTopMeta: { fontSize: 11, color: C.dim, fontFamily: FONTS.mono, minWidth: 72, textAlign: "right" },
  blueprintViewPane: { display: "flex", flexDirection: "column", gap: 12, animation: "blueprintViewIn 0.24s ease" },
  blueprintMenuIntro: { ...CARD, borderRadius: 14, padding: "14px 16px", fontSize: 13, color: C.muted, lineHeight: 1.55 },
  blueprintMenuList: { display: "grid", gridTemplateColumns: "1fr", gap: 12 },
  blueprintMenuCard: {
    ...CARD,
    borderRadius: 14,
    padding: "16px 18px",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 8,
    textAlign: "left",
    cursor: "pointer",
    transition: "background 0.15s ease",
    touchAction: "manipulation",
  },
  blueprintMenuCardTop: { display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap" },
  blueprintDailyBannerRow: {
    ...CARD,
    borderRadius: 12,
    minHeight: 46,
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    padding: "8px 12px",
    cursor: "pointer",
    textAlign: "left",
    transition: "background 0.2s ease, border-color 0.2s ease, transform 0.2s ease",
  },
  blueprintContinueBtn: {
    borderRadius: 14,
    border: "1px solid",
    minHeight: 56,
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    justifyContent: "center",
    gap: 4,
    padding: "11px 14px",
    color: "#0f1117",
    textAlign: "left",
    cursor: "pointer",
    transition: "filter 0.2s ease, transform 0.2s ease",
  },
  blueprintTrailWrap: { position: "relative", display: "flex", flexDirection: "column" },
  blueprintTrailRow: { position: "relative" },
  blueprintTrailSvg: { position: "absolute", inset: 0, width: "100%", height: "100%", pointerEvents: "none" },
  blueprintWorldNode: {
    ...CARD,
    position: "absolute",
    top: 6,
    width: "min(220px, 86vw)",
    minHeight: 82,
    borderRadius: 14,
    display: "flex",
    alignItems: "center",
    gap: 11,
    padding: "8px 10px",
    textAlign: "left",
    cursor: "pointer",
    transition: "background 0.2s ease, border-color 0.2s ease, transform 0.2s ease, opacity 0.2s ease",
  },
  blueprintNodeBadge: {
    width: 24,
    height: 24,
    borderRadius: 999,
    border: `1px solid ${C.border}`,
    background: C.surface2,
    color: C.dim,
    fontSize: 10.5,
    fontFamily: FONTS.mono,
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    textTransform: "uppercase",
  },
  blueprintNodeTitle: { fontSize: 16, color: C.textStrong, fontWeight: 700, fontFamily: FONTS.display, letterSpacing: "-0.2px" },
  blueprintNodeMeta: { fontSize: 12, color: C.dim, lineHeight: 1.4, fontFamily: FONTS.mono },
  blueprintDetailHeader: { ...CARD, borderRadius: 14, padding: "12px 14px", display: "flex", justifyContent: "space-between", gap: 12, alignItems: "center" },
  blueprintTierCard: { ...CARD, borderRadius: 14, display: "flex", flexDirection: "column", gap: 2 },
  blueprintTierHeader: {
    width: "100%",
    background: "none",
    border: "none",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
    padding: "12px 14px",
    textAlign: "left",
    minHeight: 44,
  },
  blueprintProblemRow: {
    ...CARD,
    borderRadius: 10,
    minHeight: 44,
    width: "100%",
    padding: "9px 10px",
    display: "flex",
    alignItems: "center",
    gap: 9,
    textAlign: "left",
    transition: "background 0.2s ease, border-color 0.2s ease, transform 0.2s ease",
  },
  blueprintDailyStartBtn: {
    marginTop: 4,
    width: "100%",
    minHeight: 44,
    borderRadius: 12,
    border: "1px solid rgba(245, 158, 11, 0.45)",
    color: "#0f1117",
    fontFamily: FONTS.display,
    fontSize: 15,
    fontWeight: 700,
    cursor: "pointer",
    transition: "filter 0.2s ease, transform 0.2s ease",
  },
  blueprintTabFade: {
    position: "fixed",
    left: "50%",
    transform: "translateX(-50%)",
    bottom: 64,
    width: "min(420px, calc(100vw - 32px))",
    height: 56,
    background: "linear-gradient(180deg, rgba(10, 10, 18, 0), rgba(10, 10, 18, 0.94))",
    pointerEvents: "none",
    zIndex: 20,
  },
  blueprintTabBar: {
    ...CARD,
    position: "fixed",
    left: "50%",
    transform: "translateX(-50%)",
    bottom: 16,
    width: "min(420px, calc(100vw - 32px))",
    borderRadius: 14,
    padding: 6,
    display: "grid",
    gridTemplateColumns: "1fr 1fr 1fr",
    gap: 6,
    zIndex: 21,
  },
  blueprintTabBtn: {
    minHeight: 44,
    borderRadius: 10,
    border: `1px solid transparent`,
    background: "transparent",
    color: C.dim,
    fontSize: 12,
    fontFamily: FONTS.mono,
    cursor: "pointer",
    transition: "background 0.2s ease, border-color 0.2s ease, color 0.2s ease, transform 0.2s ease",
  },
  blueprintTabBtnActive: { color: C.textStrong, borderColor: C.borderStrong, background: C.surface2 },
  blueprintPatternBadge: {
    fontSize: 11,
    fontFamily: FONTS.mono,
    color: C.dim,
    border: `1px solid ${C.border}`,
    background: C.surface2,
    borderRadius: 999,
    padding: "3px 8px",
  },
  blueprintLevelTitle: { fontSize: 17, color: C.textStrong, fontWeight: 700, fontFamily: FONTS.display, letterSpacing: "-0.2px" },
  blueprintLevelDesc: { fontSize: 13, color: C.muted, lineHeight: 1.5 },
  blueprintStarRow: { display: "flex", gap: 6, marginTop: 2, justifyContent: "center", width: "100%" },
  blueprintStar: { fontFamily: FONTS.mono, fontWeight: 700, fontSize: 14 },

  blueprintProblemCard: { ...CARD, borderRadius: 14, padding: "16px 18px", display: "flex", flexDirection: "column", gap: 10 },
  blueprintProblemText: { fontSize: 14, color: C.muted, lineHeight: 1.6 },
  blueprintExample: {
    margin: 0,
    padding: "8px 10px",
    borderRadius: 10,
    border: `1px solid ${C.border}`,
    background: C.surface2,
    color: C.textStrong,
    fontFamily: FONTS.mono,
    fontSize: 12.5,
    whiteSpace: "pre-wrap",
    lineHeight: 1.5,
  },

  blueprintSlotList: { display: "flex", flexDirection: "column", gap: 10 },
  blueprintSlot: { ...CARD, borderRadius: 12, padding: "10px 12px", borderStyle: "dashed", transition: "background 0.15s ease, border-color 0.15s ease" },
  blueprintSlotHeader: { display: "flex", alignItems: "center", gap: 8, marginBottom: 8 },
  blueprintSlotIcon: { fontSize: 11, width: 18, height: 18, borderRadius: 999, border: `1px solid ${C.border}`, display: "flex", alignItems: "center", justifyContent: "center", fontFamily: FONTS.mono, fontWeight: 700 },
  blueprintSlotName: { fontSize: 12, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.08em", fontFamily: FONTS.mono },
  blueprintSlotDesc: { fontSize: 12, color: C.dim, flex: 1 },
  blueprintSlotLimit: { fontSize: 11, color: C.dim, fontFamily: FONTS.mono },
  blueprintSlotCards: { display: "flex", flexDirection: "column", gap: 6 },
  blueprintSlotEmpty: { fontSize: 12, color: C.faint, fontStyle: "italic", padding: "4px 2px" },

  blueprintPlacedRow: { display: "flex", alignItems: "center", gap: 8 },
  blueprintPlacedCard: {
    ...CARD,
    borderRadius: 10,
    padding: "8px 10px",
    borderLeft: "3px solid transparent",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 8,
    flex: 1,
    cursor: "pointer",
    textAlign: "left",
  },
  blueprintCardCode: {
    margin: 0,
    whiteSpace: "pre-wrap",
    fontSize: 12,
    lineHeight: 1.45,
    color: C.text,
    fontFamily: FONTS.mono,
    textAlign: "left",
  },
  blueprintRemove: { fontSize: 10, color: C.faint, fontFamily: FONTS.mono, flexShrink: 0, marginTop: 2 },
  blueprintReorderCol: { display: "flex", flexDirection: "column", gap: 4 },
  blueprintReorderBtn: {
    background: C.surface2,
    border: `1px solid ${C.border}`,
    color: C.dim,
    borderRadius: 6,
    width: 44,
    height: 22,
    fontSize: 10,
    cursor: "pointer",
    fontFamily: FONTS.mono,
  },

  blueprintDeckArea: { ...CARD, borderRadius: 14, padding: "14px 16px" },
  blueprintDeckRow: { display: "flex", gap: 10, overflowX: "auto", paddingBottom: 6, WebkitOverflowScrolling: "touch" },
  blueprintDeckCard: {
    ...CARD,
    borderRadius: 10,
    padding: "10px 12px",
    minWidth: 180,
    maxWidth: 240,
    position: "relative",
    flexShrink: 0,
    cursor: "pointer",
    textAlign: "left",
    transition: "border-color 0.15s ease",
  },
  blueprintTouchGhost: {
    ...CARD,
    position: "fixed",
    top: 0,
    left: 0,
    borderRadius: 10,
    padding: "10px 12px",
    minWidth: 180,
    maxWidth: 240,
    pointerEvents: "none",
    zIndex: 1200,
    transform: "translate3d(-9999px, -9999px, 0)",
    borderColor: "var(--accent)",
    background: "rgba(17, 17, 32, 0.96)",
    boxShadow: "var(--shadow-soft)",
  },
  blueprintHintBtn: {
    position: "absolute",
    top: 6,
    right: 6,
    border: `1px solid ${C.border}`,
    background: C.surface2,
    color: C.dim,
    width: 20,
    height: 20,
    borderRadius: 999,
    fontSize: 11,
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: FONTS.mono,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  blueprintHintBubble: { marginTop: 8, fontSize: 11, color: C.dim, lineHeight: 1.45, background: C.surface2, border: `1px solid ${C.border}`, borderRadius: 8, padding: "6px 8px" },

  blueprintExecutionWrap: { display: "flex", flexDirection: "column", gap: 14, paddingBottom: 24 },
  blueprintExecCard: { ...CARD, borderRadius: 14, padding: "16px" },
  blueprintPhaseRow: { display: "flex", alignItems: "center", gap: 8, marginBottom: 10 },
  blueprintArrayRow: { display: "flex", gap: 6, flexWrap: "wrap", marginBottom: 10, justifyContent: "center" },
  blueprintArrayCellWrap: { display: "flex", flexDirection: "column", alignItems: "center", gap: 2 },
  blueprintArrayCell: {
    width: 36,
    height: 36,
    borderRadius: 8,
    border: `1px solid ${C.border}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: FONTS.mono,
    fontSize: 12,
    color: C.textStrong,
    transition: "all 0.15s ease",
  },
  blueprintArrayMarker: { fontSize: 10, color: C.faint, minHeight: 14, fontFamily: FONTS.mono },
  blueprintStateLabel: { fontSize: 11, color: C.dim, marginBottom: 6, fontWeight: 700, letterSpacing: "0.08em", textTransform: "uppercase", fontFamily: FONTS.mono },
  blueprintStateVars: { display: "flex", flexWrap: "wrap", gap: 8 },
  blueprintResultPill: { marginTop: 10, padding: "8px 10px", borderRadius: 8, border: `1px solid rgba(16, 185, 129, 0.45)`, background: "rgba(16, 185, 129, 0.08)", color: "var(--accent)", fontFamily: FONTS.mono, fontSize: 12.5 },
  blueprintTestBody: { flex: 1, fontFamily: FONTS.mono, fontSize: 12, display: "flex", flexDirection: "column", gap: 2 },
  blueprintTestLine: { color: C.muted, lineHeight: 1.4 },
  blueprintFeedbackText: { fontSize: 13, color: C.muted, lineHeight: 1.55, margin: 0 },
};
